# Generated by Django 2.0 on 2018-04-14 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bd_Gorod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Город')),
                ('kod3', models.CharField(max_length=3, verbose_name='код3')),
                ('rate', models.SmallIntegerField(default=0, verbose_name='рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='bd_Strana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Странa')),
                ('kod2', models.CharField(max_length=2, verbose_name='kod2')),
                ('kod4', models.CharField(max_length=4, verbose_name='kod4')),
                ('rate', models.SmallIntegerField(default=0, verbose_name='рейтинг')),
            ],
        ),
        migrations.AddField(
            model_name='bd_gorod',
            name='strana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bd_Strana'),
        ),
    ]
